export interface GitHubRepo {
    owner: string;
    repo: string;
}

export function parseGitHubRemote(remoteUrl: string): GitHubRepo | undefined {
    if (!remoteUrl) return undefined;

    const trimmed = remoteUrl.trim();

    const sshMatch = trimmed.match(/^git@github\.com:([^/]+)\/([^/]+?)(?:\.git)?$/);
    if (sshMatch) {
        return { owner: sshMatch[1], repo: sshMatch[2] };
    }

    const httpsMatch = trimmed.match(/^https?:\/\/(?:[^@]+@)?github\.com\/([^/]+)\/([^/]+?)(?:\.git)?(?:\/.*)?$/);
    if (httpsMatch) {
        return { owner: httpsMatch[1], repo: httpsMatch[2] };
    }

    return undefined;
}

export interface PullRequestInfo {
    prNumber: number;
    htmlUrl: string;
}

export interface CreatePullRequestArgs {
    repo: GitHubRepo;
    branch: string;
    base: string;
    title: string;
    body: string;
    token: string;
    fetchFn?: typeof fetch;
}

export async function createPullRequest(args: CreatePullRequestArgs): Promise<PullRequestInfo> {
    const fetchImpl = args.fetchFn ?? fetch;
    const url = `https://api.github.com/repos/${args.repo.owner}/${args.repo.repo}/pulls`;

    const response = await fetchImpl(url, {
        method: "POST",
        headers: {
            Authorization: `Bearer ${args.token}`,
            Accept: "application/vnd.github+json",
            "X-GitHub-Api-Version": "2022-11-28",
            "Content-Type": "application/json",
            "User-Agent": "vscode-aks-tools-kickstart",
        },
        body: JSON.stringify({
            title: args.title,
            body: args.body,
            head: args.branch,
            base: args.base,
        }),
    });

    if (!response.ok) {
        const text = await response.text();
        throw new Error(`GitHub API error ${response.status}: ${text}`);
    }

    const data = (await response.json()) as Record<string, unknown>;
    const prNumber = typeof data["number"] === "number" ? (data["number"] as number) : 0;
    const htmlUrl = typeof data["html_url"] === "string" ? (data["html_url"] as string) : "";

    if (!prNumber || !htmlUrl) {
        throw new Error(
            `GitHub API returned an unexpected response: missing PR number or URL. Raw: ${JSON.stringify(data)}`,
        );
    }

    return { prNumber, htmlUrl };
}

export function generatePRTitle(): string {
    return "feat: add AKS deployment artifacts (Kickstart)";
}

export function generatePRBody(filenames: string[]): string {
    const fileList = filenames.map((f) => `- \`${f}\``).join("\n");
    return `## AKS Kickstart

This PR contains deployment artifacts generated by the AKS Kickstart workflow.

### Files
${fileList}

### Safety
All artifacts have been validated against AKS safeguards:
- Resource limits declared on every container
- No \`:latest\` image tags
- No privileged containers or escalation
- No hostPath volumes
- No hardcoded secrets

### Next steps
1. Review the artifacts
2. Build and push your container image
3. Apply the manifests to your AKS cluster

---
Generated by [AKS Kickstart](https://github.com/Azure/vscode-aks-tools).
`;
}
