trigger: none

# The `resources` specify the location and version of the 1ES PT.
resources:
  repositories:
    - repository: 1esPipelines
      type: git
      name: 1ESPipelineTemplates/1ESPipelineTemplates
      ref: refs/tags/release

parameters:
  - name: nodeVersion
    type: string
    default: 22.x
  - name: publishVersion
    type: string
    default: 0.0.1
  - name: token
    type: string
    default: ""

extends:
  # The pipeline extends the 1ES PT which will inject different SDL and compliance tasks.
  # For non-production pipelines, use "Unofficial" as defined below.
  # For productions pipelines, use "Official".
  template: v1/1ES.Unofficial.PipelineTemplate.yml@1esPipelines
  parameters:
    # Update the pool with your team's 1ES hosted pool.
    pool:
      name: staging-pool-amd64-mariner-2
      image: 1es-azlinux-3-amd64-custom-disk
      os: linux
      hostArchitecture: amd64
    sdl:
      sourceAnalysisPool:
        name: staging-pool-amd64-mariner-2
        image: azcu-agent-amd64-windows-22-img
        os: windows
        hostArchitecture: amd64

    stages:
      - stage: Stage
        jobs:
          - job: HostJob
            # If the pipeline publishes artifacts, use `templateContext` to define the artifacts.
            # This will enable 1ES PT to run SDL analysis tools on the artifacts and then upload them.
            templateContext:
              outputs:
                - output: pipelineArtifact
                  targetPath: $(Pipeline.Workspace)/vscode-extension-unsigned
                  artifactName: vscode-extension-signed
            steps:
              # =====================================================
              # INSTALL PREREQUISITES FIRST
              # =====================================================

              - task: NodeTool@0
                displayName: Install Node.js
                retryCountOnTaskFailure: 3
                inputs:
                  versionSpec: ${{ parameters.nodeVersion }}

              # FIX: Install .NET SDK early (required for ESRP Code Signing)
              # Changed from "runtime" to "sdk" and added version specification
              - task: UseDotNet@2
                displayName: Install .NET SDK (required for ESRP signing)
                inputs:
                  packageType: "sdk"
                  version: "6.x" # Use 6.x or 8.x depending on ESRP requirements

              - checkout: self

              - bash: echo "Hello World from host"

              # =====================================================
              # BUILD AND PACKAGE
              # =====================================================

              - script: npm run install:all
                displayName: Install npm for project

              - script: npm run webpack
                displayName: Run webpack

              # Generate VSIX package
              - script: |
                  echo "Generating VSIX package..."
                  npx vsce package
                displayName: "Run for VSIX Generation"

              # List generated files (for debugging)
              - script: |
                  echo "Listing current directory contents..."
                  ls -la
                displayName: "Run list operation"

              # Find and copy the VSIX to workspace dir
              - script: |
                  set -e  # fail on error
                  echo "Finding .vsix file..."
                  VSIX_PATH=$(find . -type f -name "*.vsix" -print -quit)

                  if [ -z "$VSIX_PATH" ]; then
                    echo "❌ No .vsix file found!" >&2
                    exit 1
                  fi

                  echo "✅ Found: $VSIX_PATH"
                  mkdir -p "$(Pipeline.Workspace)/vscode-extension-unsigned"
                  cp "$VSIX_PATH" "$(Pipeline.Workspace)/vscode-extension-unsigned/"
                  echo "Copied to $(Pipeline.Workspace)/vscode-extension-unsigned/"
                displayName: "Copy VSIX to workspace directory"

              # Verify contents in workspace directory
              - script: |
                  echo "Listing workspace directory contents..."
                  ls -la "$(Pipeline.Workspace)/vscode-extension-unsigned"
                displayName: "List the unsigned dir"

              # =====================================================
              # CODE SIGNING
              # =====================================================

              - task: EsrpCodeSigning@5
                displayName: Sign VSCode extension with ESRP
                inputs:
                  ConnectedServiceName: "ESRP-AME-AZCU"
                  UseMSIAuthentication: true
                  AppRegistrationClientId: "70ebf75b-d46f-46da-90e6-1fa654251514"
                  AppRegistrationTenantId: "33e01921-4d64-4f8c-a055-5bdaffd5e33d"
                  EsrpClientId: "150f8d2b-ad88-4a27-b782-c9bc3b028430"
                  AuthAKVName: "upstreamci-ado"
                  AuthSignCertName: "azcu-ersp-corp"
                  FolderPath: $(Pipeline.Workspace)/vscode-extension-unsigned
                  Pattern: "*.vsix"
                  UseMinimatch: true
                  signConfigType: inlineSignParams
                  inlineOperation: |
                    [
                        {
                            "KeyCode" : "CP-233016",
                            "OperationCode" : "OpcSign",
                            "Parameters" : {
                                "FileDigest" : "/fd SHA256"
                            },
                            "ToolName" : "sign",
                            "ToolVersion" : "1.0"
                        },
                        {
                            "KeyCode" : "CP-233016",
                            "OperationCode" : "OpcVerify",
                            "Parameters" : {},
                            "ToolName" : "sign",
                            "ToolVersion" : "1.0"
                        }
                    ]

              # =====================================================
              # PUBLISH
              # =====================================================

              - bash: |
                  echo "=== ARTIFACT PUBLISHING DEBUG ==="
                  echo "Artifact will be published via 1ES templateContext:"
                  echo "Artifact name: vscode-extension-signed"
                  echo "Source path: $(Pipeline.Workspace)/vscode-extension-unsigned"
                  echo "Artifact contents:"
                  ls -la "$(Pipeline.Workspace)/vscode-extension-unsigned/"
                  echo "Artifact size: $(du -sh "$(Pipeline.Workspace)/vscode-extension-unsigned" 2>/dev/null || echo 'Unable to calculate')"
                  echo "Note: 1ES template will handle the actual artifact publishing"
                  echo "=== END ARTIFACT DEBUG ==="
                displayName: "Debug: Artifact Publishing"
                condition: succeeded()

              - task: Bash@3
                displayName: "Publish VSIX to Marketplace"
                inputs:
                  targetType: inline
                  script: |
                    set -e
                    echo "Checking VSCE version..."
                    npx vsce --version
                    echo "Listing VSCE packages..."
                    npx vsce ls
                    echo "Showing VSCE extension info..."
                    npx vsce show ms-kubernetes-tools.vscode-aks-tools

                    echo "Finding VSIX..."
                    VSIX_PATH=$(find "$(Pipeline.Workspace)/vscode-extension-unsigned/" -type f -name "*.vsix" | head -n 1)

                    echo "Publishing VSIX package: $VSIX_PATH"
                    echo "Using PAT: ${TOKEN:0:4}**** (masked)"

                    npx vsce publish --pat "$TOKEN" --packagePath "$VSIX_PATH"
                env:
                  TOKEN: ${{ parameters.token }}

              - task: GithubRelease@1
                displayName: "Create GitHub Release"
                inputs:
                  gitHubConnection: Kubernetes (9)
                  repositoryName: Azure/vscode-aks-tools
                  action: create
                  title: ${{ parameters.publishVersion }}
                  tagSource: userSpecifiedTag
                  tag: ${{ parameters.publishVersion }}
                  assets: |
                    $(Pipeline.Workspace)/vscode-extension-unsigned/vscode-aks-tools-*.vsix
