apiVersion: v1
kind: Pod
metadata:
  name: debug-aks-agentpool-52310376-vmss000008
  namespace: default
spec:
  containers:
  - args: ["-c", "sleep infinity"]
    command: ["/bin/sh"]
    image: docker.io/corfr/tcpdump
    imagePullPolicy: IfNotPresent
    name: debug
    resources: {}
    securityContext:
      privileged: true
      runAsUser: 0
    volumeMounts:
    - mountPath: /host
      name: host-volume
  volumes:
  - name: host-volume
    hostPath:
      path: /
  dnsPolicy: ClusterFirst
  nodeSelector:
    kubernetes.io/hostname: aks-agentpool-52310376-vmss000008
  restartPolicy: Never
  securityContext: {}
  hostIPC: true
  hostNetwork: true
  hostPID: true