name: ChatGPT Review

on:
  pull_request:
    types: [opened, reopened, edited, ready_for_review]
    branches:
      - 'master'

jobs:
  chatgpt-review:
    name: ChatGPT Review
    runs-on: ubuntu-latest
    steps:
    - uses: feiskyer/ChatGPT-Reviewer@v0.3
      name: ChatGPT Review
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        OPENAI_API_KEY: ${{ secrets.VS_OPENAI_API_KEY }}
